# Generated by Django 4.2.6 on 2023-11-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=30, verbose_name='Category')),
                ('url', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=30, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=12, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.CharField(max_length=200, verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('url', models.SlugField(unique=True, verbose_name='Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='subcategory/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length')),
                ('spokes', models.CharField(blank=True, max_length=10, verbose_name='Spokes')),
                ('hook', models.CharField(blank=True, max_length=10, verbose_name='Hook')),
                ('material', models.CharField(max_length=200)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='shop.category', verbose_name='Category')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='shop.country', verbose_name='Country')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer', to='shop.producer', verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='YarnImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Name')),
                ('image', models.ImageField(upload_to='yarnimages/', verbose_name='Image')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory', verbose_name='SubCategory')),
            ],
            options={
                'verbose_name': 'YarnImage',
                'verbose_name_plural': 'YarnImages',
            },
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('url', models.SlugField(unique=True, verbose_name='Url')),
                ('image', models.ImageField(upload_to='yarn/', verbose_name='Image')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Time_add')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time_update')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Category')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color', to='shop.color', verbose_name='Color')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.country', verbose_name='Country')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.producer', verbose_name='Producer')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='shop.subcategory', verbose_name='SubCategory')),
            ],
            options={
                'verbose_name': 'Yarn',
                'verbose_name_plural': 'Yarns',
            },
        ),
    ]
