# Generated by Django 4.2.6 on 2023-11-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=30)),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='subcategory/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spokes', models.CharField(blank=True, max_length=10)),
                ('hook', models.CharField(blank=True, max_length=10)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='shop.category')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='shop.country')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer', to='shop.producer')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.SlugField(unique=True)),
                ('time_add', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('availability', models.BooleanField(default=True)),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color', to='shop.color')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='shop.subcategory')),
            ],
            options={
                'verbose_name': 'Yarn',
                'verbose_name_plural': 'Yarns',
            },
        ),
        migrations.CreateModel(
            name='YarnImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='shop/')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.yarn')),
            ],
            options={
                'verbose_name': 'YarnImage',
                'verbose_name_plural': 'YarnImages',
            },
        ),
    ]
