# Generated by Django 4.2.6 on 2023-11-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('url', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='shop/')),
                ('price', models.SmallIntegerField()),
                ('length', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('needles', models.CharField(max_length=50)),
                ('hook', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_name', to='shop.color')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_name', to='shop.producer')),
            ],
        ),
        migrations.CreateModel(
            name='YarnImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='shop/')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.yarn')),
            ],
        ),
    ]
