# Generated by Django 4.2.6 on 2023-11-06 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'Producer', 'verbose_name_plural': 'Producers'},
        ),
        migrations.AlterModelOptions(
            name='yarn',
            options={'verbose_name': 'Yarn', 'verbose_name_plural': 'Yarns'},
        ),
        migrations.AlterModelOptions(
            name='yarnimages',
            options={'verbose_name': 'YarnImage', 'verbose_name_plural': 'YarnImages'},
        ),
        migrations.AddField(
            model_name='yarn',
            name='yarn_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='yarn_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
