# Generated by Django 4.2.6 on 2023-11-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_yarns', to='shop.subcategory', verbose_name='SubCategory'),
        ),
    ]
