# Generated by Django 4.2.6 on 2023-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='image',
            field=models.ImageField(default=1, upload_to='yarn/'),
            preserve_default=False,
        ),
    ]
