# Generated by Django 4.2.6 on 2023-11-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_yarn_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnimages',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory'),
        ),
    ]
