# Generated by Django 4.2.6 on 2024-02-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_yarn_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='count',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='prod',
        ),
    ]
