# Generated by Django 4.2.6 on 2023-11-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_subcategory_name_alter_yarn_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='color',
            name='col',
            field=models.CharField(max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='country',
            name='count',
            field=models.CharField(max_length=12, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='prod',
            field=models.CharField(max_length=200, verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='shop.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='shop.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='hook',
            field=models.CharField(blank=True, max_length=10, verbose_name='Hook'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='subcategory/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer', to='shop.producer', verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='spokes',
            field=models.CharField(blank=True, max_length=10, verbose_name='Spokes'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='col',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color', to='shop.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='image',
            field=models.ImageField(upload_to='yarn/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='shop.subcategory', verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time_add'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time_update'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='yarnimages',
            name='image',
            field=models.ImageField(upload_to='yarnimages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='yarnimages',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='yarnimages',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory', verbose_name='Yarn'),
        ),
    ]
