# Generated by Django 4.2.6 on 2023-11-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_cat_alter_category_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yarnimages',
            old_name='yarn',
            new_name='subcat',
        ),
    ]
