# Generated by Django 4.2.6 on 2023-11-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_yarn_yarnimages_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarn',
            name='material',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
