# Generated by Django 4.2.6 on 2023-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_yarn_cat_yarn_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='country',
            name='count',
            field=models.CharField(max_length=12, verbose_name='Country'),
        ),
    ]
