# Generated by Django 4.2.6 on 2023-11-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_cat_alter_country_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='material',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='material',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
