# Generated by Django 4.2.6 on 2023-11-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_yarn_material_subcategory_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='cat',
        ),
        migrations.AddField(
            model_name='yarn',
            name='count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarn',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.producer', verbose_name='Producer'),
            preserve_default=False,
        ),
    ]
