# Generated by Django 4.2.6 on 2023-11-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_yarn_cat_yarn_count_yarn_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
