# Generated by Django 4.2.6 on 2023-11-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_yarn_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnimages',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory', verbose_name='SubCategory'),
        ),
    ]
