# Generated by Django 4.2.6 on 2023-11-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_yarnimages_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnimages',
            name='subcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory', verbose_name='SubCategory'),
            preserve_default=False,
        ),
    ]
